export const GENESIS_TIMESTAMP = 1774310400000;

export const BLOCK_TYPES = {
    TRANSACTION: 'TRANSACTION',
    STORAGE_CONTRACT: 'STORAGE_CONTRACT',
    STAKING_CONTRACT: 'STAKING_CONTRACT',
    SLASHING_TRANSACTION: 'SLASHING_TRANSACTION',
    CHECKPOINT: 'CHECKPOINT'
} as const;
