version: '3.8'

services:
  mongodb:
    image: mongo:7.1
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
      
  verimus-node:
    build: .
    restart: unless-stopped
    ports:
      - "26780:26780"
    volumes:
      - node_data:/usr/src/app/data
      - node_keys:/usr/src/app/keys
    environment:
      # Explicit Mongo lookup routing container mesh
      - MONGO_URI=mongodb://mongodb:27017
    # You may easily map arbitrary discovery parameters into this start command
    # e.g: command: --mongo-host mongodb --port 26780 --discover 192.168.1.100:26780
    command: --mongo-host mongodb --port 26780 --public-address 127.0.0.1:26780 --storage-type local --data-dir /usr/src/app/data
    depends_on:
      - mongodb

volumes:
  mongo_data:
  node_data:
  node_keys:
