version: '3.8'

services:
  mongodb:
    image: mongo:7.1
    ports:
      - "27018:27017"
    tmpfs:
      - /data/db
    command: --bind_ip_all

  # Extensible Local Developer Node Mapping Live Code Volume Overrides
  verimus-dev-node:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/ui/node_modules
    ports:
      - "26780:26780"
    # Watches typescript arrays executing dynamically over fast-restart triggers
    command: npm run watch:node -- --mongo-host mongodb --mongo-port 27017 --port 26780 --public-address 127.0.0.1:26780
    depends_on:
      - mongodb
